### ISSUE TITLE
Bloc Library benchmarks appear inaccurate

### ISSUE THREAD

**Issue by felangel** [jonataslaw/benchmarks#5] opened 2020-06-15 06:13 UTC
Hi 👋 

I forked the repo, adjusted the bloc library sample to be more consistent with what the get sample was doing and opened #4 (related to #1, #2, and https://github.com/jonataslaw/get/issues/243).

I then profiled the memory usage for the sample app using get vs the sample app using the bloc library and got the following results:

**Total Memory Consumption:**
bloc library: ~544 bytes
get: ~960 bytes

**Get**
<img width="1138" alt="get" src="https://user-images.githubusercontent.com/8855632/84623323-a5567e00-aea4-11ea-9998-63cb3e7edf72.png">

**Bloc Library**
<img width="1123" alt="bloc-library" src="https://user-images.githubusercontent.com/8855632/84623324-a7204180-aea4-11ea-9228-43de5dbd2816.png">

I would really appreciate it if you could update this repository as well as the [get documentation](https://github.com/jonataslaw/get/tree/master/benchmark) accordingly.

I personally feel statements like

> GetBuilder is very economical in RAM, and there is hardly a more economical approach than him (at least I can't imagine one, if it exists, please let us know).

are misleading and should be removed. Let me know what you think, thanks 🙏

**Comment by jonataslaw** [comment] 2020-06-15 07:32
Hi, it is very strange to have remnants of a dependency that has not even been used. In your print there are items from the route manager, which is not used in this project, and is not even compiled for AOT.
But maybe it could be caching an old version of get, I changed Get to the beta version (which is now the current stable) and removed the "^" to prevent this from happening, because this is strange.
I accepted his pull, and Remi's, and redid the benchmarks. With its version, flutter_bloc looks much better, thanks for redoing it, nobody better than the creator of the package to know how to use it.
However it seems that there was a regression with Remi's, Consumer looked better than context.watch, if he regresses that, I change the tests.
Anyway, these are the new numbers, I recommend that you clone the repository, and give it a flutter clean first.
And I will not remove this information because it is true, and it will continue to be for a long time hahaha.

![flutterbloc](https://user-images.githubusercontent.com/35742643/84629630-0429f080-aec1-11ea-9005-023ee9c180b2.png)
![mobx](https://user-images.githubusercontent.com/35742643/84629638-0ab86800-aec1-11ea-8018-056f740a69e9.png)
![redux](https://user-images.githubusercontent.com/35742643/84629640-0db35880-aec1-11ea-8271-2b2f8d7349a9.png)
![provider](https://user-images.githubusercontent.com/35742643/84629656-1310a300-aec1-11ea-9c76-bcece0777700.png)
![get](https://user-images.githubusercontent.com/35742643/84629688-1f94fb80-aec1-11ea-9215-ba72865fb8e5.png)
![getx](https://user-images.githubusercontent.com/35742643/84629700-23288280-aec1-11ea-909b-334ce47fbde1.png)

**Comment by jonataslaw** [comment] 2020-06-15 08:48
I think that this is now resolved and clarified. Closing it.

**Closed by jonataslaw** 2020-06-15 08:48 UTC

**Comment by rrousselGit** [comment] 2020-06-15 08:51
> However it seems that there was a regression with Remi's, Consumer looked better than context.watch, if he regresses that, I change the tests.

It being a regression is impossible, considering  Consumer works by calling context.watch.

At best, this says that there's a problem with the way values are measured.

**Comment by jonataslaw** [comment] 2020-06-15 08:55
> > However it seems that there was a regression with Remi's, Consumer looked better than context.watch, if he regresses that, I change the tests.
> 
> It being a regression is impossible, considering Consumer works by calling context.watch.
> 
> At best, this says that there's a problem with the way values are measured.

The difference is that before you were rebuilding ListView.builder, and by calling context.watch you are building the entire Page class.
At least I could not see any improvement in this approach, but I may be mistaken, you are the creator of the lib, you must know the best approach for it.

**Comment by rrousselGit** [comment] 2020-06-15 08:58
The test is for RAM, not cpu. 
That has no impact.

Memory wise it removes one widget and one State instance, so that can only be better.
If it's not, it's a problem with how values are measured.

**Comment by jonataslaw** [comment] 2020-06-15 09:15
Well, I think you must be right. This should make some significant difference when the collector removes the garbage generated with each markNeedBuild() (which also consumes RAM), and in the same way that you removed the StatefulWidget from the Provider, I removed from Get, further reducing the consumption of Get, so that must have made that impression on me.
I'm going to work now, anything open issue/PR that later I see.

**Comment by rrousselGit** [comment] 2020-06-15 09:32
Also:
Before, the Consumer was above `ListView` so the entire ListView.builder was rebuilt on change too, like with all other currently tested packages.

To begin with, the fact that we have a difference measured in tens of kb between packages doesn't make sense.

The `class AppState extends ChangeNotifier` instance weight 32 bytes. A Consumer + its Element costs a few hundred bytes at best.
We're nowhere near a difference of 10'000  bytes.

**Comment by rrousselGit** [comment] 2020-06-15 09:48
There's **definitely** a problem with how the memory is measured.

I've just changed provider's test to:

```dart
class ListViewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      padding: EdgeInsets.fromLTRB(0.0, 8.0, 0.0, 8.0),
      itemBuilder: (context, index) {
        return Builder(
          builder: (context) {
            final title = context.select((AppState s) => s.items[index].title);

            return ListTile(
              title: Text(title),
            );
          },
        );
      },
    );
  }
}
```


And now `provider` 300kb less than `get`, when it should consume more memory than before (as I've added one StatelessWidget + selector per item).
